### ISSUE TITLE
umtrx can not build against recent uhd release - no msg.hpp

### ISSUE THREAD

**Issue by guruofquality** [fairwaves/UHD-Fairwaves#21]
Some of the logging api changed, and `<uhd/utils/msg.hpp>` is no longer present. I had to fix this with soapy uhd, the logging usage looks like this now: https://github.com/pothosware/SoapyUHD/blob/master/UHDSoapyDevice.cpp#L837

**Comment by clebig** [comment]
Hi !
Is there a workaround that could help in building the current sources in master ?

Thank you.

**Comment by chemeris** [comment]
@clebig Not yet, unfortunately. Someone has to write a patch to replace all `UHD_MSG` with `UHD_LOG_*`. If you write one, please send us a Pull Request here.

**Comment by clebig** [comment]
Hi @chemeris ,
Thanks for your reply. Which version of UHD should I use to compile the UHD-Fairwaves driver ?
Is UHD-3.9.LTS a good candidate ?
I will look at the code if I find the time next week.

**Comment by clebig** [comment]
Is there any plan to update UHD-Fairwaves tree in the future to be usable with recent versions of UHD ?

**Comment by ibra1212** [comment]
I'm working with the UmTRX 2.1 with openBTS recently. i am trying to install the UHD module of faiwaves but i have this error:

/home/openbts/UHD-Fairwaves-1.0.18/host/cores/super_recv_packet_handler.hpp:27:32: fatal error: uhd / utils / atomic.hpp: No files or folders of this type

Can you help me please?

**Comment by clebig** [comment]
Build and install the branch UHD-3.9.LTS of their github repo

github.com/EttusResearch/uhd.git

**Comment by ibra1212** [comment]
Hi clebig, thanks for the quick reply I tested with UHD-3.9.LTS with this link github.com/EttusResearch/uhd.git always using the UHD-Fairwaves module, but the same error message appears.

**Comment by ibra1212** [comment]
Hi clebig, thanks for the quick reply I tested with UHD-3.9.LTS with this link github.com/EttusResearch/uhd.git always using the UHD-Fairwaves module, but the same error message appears.

**Comment by clebig** [comment]
First, you need to uninstall any previous uhd installation. Then compile
and build UHD-3.9.LTS.  Once you have cloned the repo, don't forget to "git
checkout UHD-3.9.LTS" Before building it.

**Comment by ibra1212** [comment]
I just followed your advice, I made the make but there were errors concerning the compiler -std = c ++ 11 that I could solve. the make works wonderfully now. A big thank you for your valuable help.

**Comment by ibra1212** [comment]
> @clebig Not yet, unfortunately. Someone has to write a patch to replace all `UHD_MSG` with `UHD_LOG_*`. If you write one, please send us a Pull Request here.

how can we do it  ?

**Comment by clebig** [comment]
Something tells me that something good will happen quite soon regarding
this issue...

In the meantime, you can still compile this code with UHD-3.9.LTS.

**Comment by chemeris** [comment]
I've just merged several fixes and it should now compile both for old and new UHD versions.

Specifically, I've tested with UHD 3.10 (Ubuntu 18.04 default) and UHD 3.14 (the latest from Ettus Research PPA).

I'm closing this issue - if you have any issues with the new UHD versions - please reopen.

**Comment by clebig** [comment]
:-), thanks a lot Alexander ! I'll test it on Monday. Which version of GCC
and libboost have you used ?

Clement

**Comment by chemeris** [comment]
Everything is from latest Ubuntu 18.04 repo except UHD:
gcc 7.4.0
Boost 1.65.1

**Comment by clebig** [comment]
It compiles correctly now on x86_64 on debian 10 with the following tools : 
UHD 3.14
cmake 3.13
libboost 1.67
gcc 8.3 / libstdc++ 8.3

I will try a compilation on rapsbian 10.

**Comment by bbaranoff** [comment]
> It compiles correctly now on x86_64 on debian 10 with the following tools : UHD 3.14 cmake 3.13 libboost 1.67 gcc 8.3 / libstdc++ 8.3
> 
> It also compiles on Raspbian Buster with UHD 3.14 (some tweaking needed to compile UHD from ettus' repo) cmake 3.13 libboost 1.67 gcc 8.3 / libstdc++ 8.3
> 
> umtrx_test_chains runs on both.

Against 3.14

```bash
nirvana@hp:~/uhd$ sudo locate msg.hpp
/home/nirvana/uhd/host/lib/deps/rpclib/include/rpc/msgpack/preprocessor/assert_msg.hpp
/home/nirvana/uhd/host/lib/include/uhdlib/rfnoc/async_msg.hpp
/usr/include/boost/preprocessor/assert_msg.hpp
/usr/include/boost/spirit/home/support/assert_msg.hpp
```
