### ISSUE TITLE
umtrx fails to build with boost 1.66

### ISSUE THREAD

**Issue by pespin** [fairwaves/UHD-Fairwaves#22]
Running archlinux with boost 1.66.0-2, compilation fails.

```
/UHD-Fairwaves/host/umtrx_monitor.cpp: In member function ‘void umtrx_impl::server_query_handler()’:
/UHD-Fairwaves/host/umtrx_monitor.cpp:121:58: error: ‘class boost::asio::basic_socket_acceptor<boost::asio::ip::tcp>’ has no member named ‘native’
     if (not wait_read_sockfd(_server_query_tcp_acceptor->native(), 100)) return;
                                                          ^~~~~~
/UHD-Fairwaves/host/umtrx_monitor.cpp: At global scope:
/UHD-Fairwaves/host/umtrx_monitor.cpp:86:13: warning: ‘bool wait_read_sockfd(int, size_t)’ defined but not used [-Wunused-function]
 static bool wait_read_sockfd(const int sockfd, const size_t timeoutMs)
             ^~~~~~~~~~~~~~~~
```
